apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webmvc.eshop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webmvc
            port:
              number: 80
  - host: webstatus.eshop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webstatus
            port:
              number: 80