apiVersion: v1
kind: ConfigMap
metadata:
  name: external-links
  namespace: eshop-apis
  labels:
    app.kubernetes.io/part-of: eshop
    tier: api
data:
  PURCHASE_URL: "http://webshoppingapigw"
  ESHOP_STORAGE_CATALOG_URL: "http://webshoppingapigw/c/api/v1/catalog/items/[0]/pic/"