name: location-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Location/**
    - .github/workflows/location-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Location/**
    - .github/workflows/location-api.yml

env:
  SERVICE: location-api
  IMAGE: location.api

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ secrets.REGISTRY_HOST }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.USERNAME }}
        registry_password: ${{ secrets.PASSWORD }}
